"""empty message

Revision ID: 5326832e868d
Revises: bcce5a6705f9
Create Date: 2022-08-12 12:13:31.657317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5326832e868d'
down_revision = 'bcce5a6705f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('artist', sa.Column('looking_venues', sa.String(length=5), nullable=True))
    op.add_column('artist', sa.Column('seeking_description', sa.String(length=250), nullable=True))
    op.add_column('venue', sa.Column('geners', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('venue', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('venue', sa.Column('looking_talent', sa.String(length=5), nullable=True))
    op.add_column('venue', sa.Column('seeking_description', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'seeking_description')
    op.drop_column('venue', 'looking_talent')
    op.drop_column('venue', 'website_link')
    op.drop_column('venue', 'geners')
    op.drop_column('artist', 'seeking_description')
    op.drop_column('artist', 'looking_venues')
    op.drop_column('artist', 'website_link')
    # ### end Alembic commands ###
