"""empty message

Revision ID: 75202a0b8e65
Revises: caf5688f01fb
Create Date: 2022-08-12 12:33:51.076795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75202a0b8e65'
down_revision = 'caf5688f01fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('geners', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('artist', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('artist', 'geners')
    # ### end Alembic commands ###
